apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: go-con-coche

resources:
  - deployment.yml
  - service.yml
  - configmap.yml
  - mailhog.yml

images:
  - name: peraltamorena/go-con-coche-app
    newTag: sha-b6ba9af

namePrefix: go-con-coche-

labels:
  - pairs:
      app: go-con-coche
      version: v1.1.1

replicas:
  - name: app
    count: 1
